# Generated by Django 4.2 on 2025-10-30 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '寰呭鏍?), ('approved', '瀹℃牳閫氳繃'), ('rejected', '瀹℃牳鎷掔粷')], default='pending', max_length=20, verbose_name='瀹℃牳鐘舵€?)),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='瀹℃牳澶囨敞')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='瀹℃牳鏃堕棿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='鍒涘缓鏃堕棿')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='鏇存柊鏃堕棿')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_reviews', to=settings.AUTH_USER_MODEL, verbose_name='瀹℃牳鍛?)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reviews', to='vehicles.vehicle', verbose_name='杞﹁締')),
            ],
            options={
                'verbose_name': '杞﹁締瀹℃牳',
                'verbose_name_plural': '杞﹁締瀹℃牳',
                'db_table': 'vehicle_reviews',
            },
        ),
        migrations.CreateModel(
            name='UserAuthenticationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '寰呭鏍?), ('approved', '瀹℃牳閫氳繃'), ('rejected', '瀹℃牳鎷掔粷')], default='pending', max_length=20, verbose_name='瀹℃牳鐘舵€?)),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='瀹℃牳澶囨敞')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='瀹℃牳鏃堕棿')),
                ('id_number_snapshot', models.CharField(blank=True, max_length=18, null=True, verbose_name='韬唤璇佸彿蹇収')),
                ('id_front_image_snapshot', models.ImageField(blank=True, null=True, upload_to='review_id_images/', verbose_name='韬唤璇佹闈㈠揩鐓?)),
                ('id_back_image_snapshot', models.ImageField(blank=True, null=True, upload_to='review_id_images/', verbose_name='韬唤璇佸弽闈㈠揩鐓?)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='鍒涘缓鏃堕棿')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='鏇存柊鏃堕棿')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_reviews_made', to=settings.AUTH_USER_MODEL, verbose_name='瀹℃牳鍛?)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_reviews', to=settings.AUTH_USER_MODEL, verbose_name='鐢ㄦ埛')),
            ],
            options={
                'verbose_name': '鐢ㄦ埛璁よ瘉瀹℃牳',
                'verbose_name_plural': '鐢ㄦ埛璁よ瘉瀹℃牳',
                'db_table': 'user_auth_reviews',
            },
        ),
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('vehicle', '杞﹁締淇℃伅涓炬姤'), ('user', '鐢ㄦ埛琛屼负涓炬姤'), ('fraud', '娆鸿瘓琛屼负涓炬姤'), ('other', '鍏朵粬涓炬姤')], max_length=20, verbose_name='涓炬姤绫诲瀷')),
                ('title', models.CharField(max_length=200, verbose_name='涓炬姤鏍囬')),
                ('description', models.TextField(verbose_name='涓炬姤鎻忚堪')),
                ('evidence_images', models.JSONField(default=list, verbose_name='璇佹嵁鍥剧墖')),
                ('status', models.CharField(choices=[('pending', '寰呭鐞?), ('processing', '澶勭悊涓?), ('resolved', '宸插鐞?), ('dismissed', '宸插拷鐣?)], default='pending', max_length=20, verbose_name='澶勭悊鐘舵€?)),
                ('handling_note', models.TextField(blank=True, null=True, verbose_name='澶勭悊澶囨敞')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='鍒涘缓鏃堕棿')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='鏇存柊鏃堕棿')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='瑙ｅ喅鏃堕棿')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL, verbose_name='澶勭悊浜?)),
                ('reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='琚妇鎶ョ敤鎴?)),
                ('reported_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='vehicles.vehicle', verbose_name='琚妇鎶ヨ溅杈?)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='涓炬姤浜?)),
            ],
            options={
                'verbose_name': '绯荤粺涓炬姤',
                'verbose_name_plural': '绯荤粺涓炬姤',
                'db_table': 'system_reports',
            },
        ),
        migrations.CreateModel(
            name='AdminOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('vehicle_approve', '瀹℃牳閫氳繃杞﹁締'), ('vehicle_reject', '瀹℃牳鎷掔粷杞﹁締'), ('user_auth_approve', '瀹℃牳閫氳繃鐢ㄦ埛璁よ瘉'), ('user_auth_reject', '瀹℃牳鎷掔粷鐢ㄦ埛璁よ瘉'), ('report_handle', '澶勭悊涓炬姤'), ('user_ban', '灏佺鐢ㄦ埛'), ('user_unban', '瑙ｅ皝鐢ㄦ埛'), ('vehicle_remove', '涓嬫灦杞﹁締'), ('system_config', '绯荤粺閰嶇疆淇敼'), ('other', '鍏朵粬鎿嶄綔')], max_length=50, verbose_name='鎿嶄綔绫诲瀷')),
                ('target_type', models.CharField(max_length=20, verbose_name='鐩爣绫诲瀷')),
                ('target_id', models.IntegerField(verbose_name='鐩爣ID')),
                ('description', models.TextField(verbose_name='鎿嶄綔鎻忚堪')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP鍦板潃')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='鐢ㄦ埛浠ｇ悊')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='鍒涘缓鏃堕棿')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_operations', to=settings.AUTH_USER_MODEL, verbose_name='绠＄悊鍛?)),
            ],
            options={
                'verbose_name': '绠＄悊鍛樻搷浣滄棩蹇?,
                'verbose_name_plural': '绠＄悊鍛樻搷浣滄棩蹇?,
                'db_table': 'admin_operation_logs',
            },
        ),
        migrations.AddIndex(
            model_name='vehiclereview',
            index=models.Index(fields=['status', '-created_at'], name='vehicle_rev_status_0fad8a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclereview',
            index=models.Index(fields=['reviewer', '-review_time'], name='vehicle_rev_reviewe_71b8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthenticationreview',
            index=models.Index(fields=['status', '-created_at'], name='user_auth_r_status_933389_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthenticationreview',
            index=models.Index(fields=['reviewer', '-review_time'], name='user_auth_r_reviewe_4f63e9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemreport',
            index=models.Index(fields=['status', '-created_at'], name='system_repo_status_2395e5_idx'),
        ),
        migrations.AddIndex(
            model_name='systemreport',
            index=models.Index(fields=['report_type', '-created_at'], name='system_repo_report__82003a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemreport',
            index=models.Index(fields=['handler', '-updated_at'], name='system_repo_handler_62f0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='adminoperationlog',
            index=models.Index(fields=['admin', '-created_at'], name='admin_opera_admin_i_8981bd_idx'),
        ),
        migrations.AddIndex(
            model_name='adminoperationlog',
            index=models.Index(fields=['operation_type', '-created_at'], name='admin_opera_operati_46bcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='adminoperationlog',
            index=models.Index(fields=['target_type', 'target_id'], name='admin_opera_target__3bc05c_idx'),
        ),
    ]

