# Generated by Django 4.2 on 2025-11-01 02:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('user_type', models.CharField(choices=[('buyer', '买家'), ('seller', '卖家'), ('admin', '管理员')], default='buyer', max_length=20, verbose_name='用户类型')),
                ('account_status', models.CharField(choices=[('normal', '正常'), ('disabled', '禁用'), ('frozen', '冻结')], default='normal', max_length=20, verbose_name='账户状态')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, null=True, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='所在地区')),
                ('real_name_auth_status', models.CharField(choices=[('unverified', '未认证'), ('pending', '待审核'), ('verified', '已认证'), ('rejected', '认证拒绝')], default='unverified', max_length=20, verbose_name='实名认证状态')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='id_images/', verbose_name='身份证正面')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='id_images/', verbose_name='身份证反面')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户人名称')),
                ('bank_card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='银行卡号')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户行')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('failed_login_count', models.IntegerField(default=0, verbose_name='失败登录次数')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='最后失败登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='搜索关键词')),
                ('search_params', models.JSONField(default=dict, verbose_name='搜索参数')),
                ('search_time', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '搜索历史',
                'verbose_name_plural': '搜索历史',
                'db_table': 'user_search_history',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchases', models.IntegerField(default=0, verbose_name='总购买数')),
                ('total_sales', models.IntegerField(default=0, verbose_name='总销售数')),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='平均评分')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='评价总数')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='店铺名称')),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='店铺logo')),
                ('shop_description', models.TextField(blank=True, null=True, verbose_name='店铺描述')),
                ('shop_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='店铺电话')),
                ('shop_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺地址')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='账户余额')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='冻结余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('register', '注册'), ('password_change', '修改密码'), ('info_update', '更新信息'), ('vehicle_upload', '上传车辆'), ('vehicle_delete', '删除车辆'), ('place_order', '下订单'), ('cancel_order', '取消订单'), ('other', '其他')], max_length=50, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.CharField(max_length=500, verbose_name='用户代理')),
                ('status', models.CharField(choices=[('success', '成功'), ('failure', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'user_operation_logs',
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.CharField(max_length=500, verbose_name='用户代理')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='登出时间')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'db_table': 'user_login_history',
            },
        ),
        migrations.CreateModel(
            name='UserBrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(verbose_name='车辆ID')),
                ('browse_time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('duration', models.IntegerField(default=0, verbose_name='浏览时长（秒）')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史',
                'db_table': 'user_browsing_history',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('district', models.CharField(max_length=50, verbose_name='区')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮编')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'user_addresses',
            },
        ),
        migrations.AddIndex(
            model_name='usersearchhistory',
            index=models.Index(fields=['user', '-search_time'], name='user_search_user_id_aca263_idx'),
        ),
        migrations.AddIndex(
            model_name='useroperationlog',
            index=models.Index(fields=['user', '-created_at'], name='user_operat_user_id_625a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginhistory',
            index=models.Index(fields=['user', '-login_time'], name='user_login__user_id_79a272_idx'),
        ),
        migrations.AddIndex(
            model_name='userbrowsinghistory',
            index=models.Index(fields=['user', '-browse_time'], name='user_browsi_user_id_44b86f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status'], name='users_account_33da0c_idx'),
        ),
    ]
