# Generated by Django 4.2 on 2025-11-05 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='交易密码'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('transaction_type', models.CharField(choices=[('recharge', '充值'), ('purchase', '购买'), ('refund', '退款')], max_length=20, verbose_name='交易类型')),
                ('payment_method', models.CharField(blank=True, choices=[('wechat', '微信'), ('alipay', '支付宝'), ('bank', '银行卡')], max_length=20, null=True, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联订单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '钱包交易记录',
                'verbose_name_plural': '钱包交易记录',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['user', '-created_at'], name='wallet_tran_user_id_1da2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'),
        ),
    ]
