# Generated by Django 4.2 on 2025-11-01 02:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品牌名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='品牌logo')),
                ('country', models.CharField(choices=[('china', '中国'), ('import', '进口')], default='import', max_length=50, verbose_name='国家/地区')),
                ('description', models.TextField(blank=True, null=True, verbose_name='品牌描述')),
                ('official_website', models.URLField(blank=True, null=True, verbose_name='官方网站')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车品牌',
                'verbose_name_plural': '车品牌',
                'db_table': 'car_brands',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='type_icons/', verbose_name='图标')),
                ('order_weight', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vehicles.cartype', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '车类型',
                'verbose_name_plural': '车类型',
                'db_table': 'car_types',
                'ordering': ['order_weight', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=30, unique=True, verbose_name='VIN码')),
                ('model_name', models.CharField(max_length=100, verbose_name='车型名称')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='年份')),
                ('color', models.CharField(max_length=50, verbose_name='车身颜色')),
                ('transmission', models.CharField(choices=[('manual', '手动'), ('auto', '自动'), ('cvt', 'CVT')], max_length=20, verbose_name='变速箱')),
                ('emission_standard', models.CharField(choices=[('euro1', '欧I'), ('euro2', '欧II'), ('euro3', '欧III'), ('euro4', '欧IV'), ('euro5', '欧V'), ('euro6', '欧VI')], max_length=50, verbose_name='排放标准')),
                ('fuel_type', models.CharField(choices=[('gasoline', '汽油'), ('diesel', '柴油'), ('electric', '电动'), ('hybrid', '混合动力')], max_length=50, verbose_name='燃油类型')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='行驶里程(km)')),
                ('plate_date', models.DateField(verbose_name='上牌时间')),
                ('first_owner_date', models.DateField(blank=True, null=True, verbose_name='首次过户时间')),
                ('description', models.TextField(verbose_name='车况描述')),
                ('highlights', models.JSONField(default=list, verbose_name='亮点标签')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('listed', '在售'), ('sold', '已售'), ('delisted', '已下架'), ('maintenance', '维修中'), ('rejected', '审核拒绝')], default='draft', max_length=20, verbose_name='车辆状态')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('listed_at', models.DateTimeField(blank=True, null=True, verbose_name='上架时间')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.carbrand', verbose_name='品牌')),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.cartype', verbose_name='车型类型')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehiclePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='旧价格')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新价格')),
                ('change_reason', models.CharField(max_length=255, verbose_name='变化原因')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变化时间')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='vehicles.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '价格变化历史',
                'verbose_name_plural': '价格变化历史',
                'db_table': 'vehicle_price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='建议价格')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低价格')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高价格')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='置信度')),
                ('pricing_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='定价模型版本')),
                ('pricing_reason', models.TextField(blank=True, null=True, verbose_name='定价依据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='vehicles.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆定价',
                'verbose_name_plural': '车辆定价',
                'db_table': 'vehicle_prices',
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/', verbose_name='图片')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='vehicle_thumbnails/', verbose_name='缩略图')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否为主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '车辆照片',
                'verbose_name_plural': '车辆照片',
                'db_table': 'vehicle_photos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('review_type', models.CharField(choices=[('seller', '对卖家的评价'), ('buyer', '对买家的评价'), ('vehicle', '对车辆的评价')], default='seller', max_length=20, verbose_name='评价类型')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('seller_reply', models.TextField(blank=True, null=True, verbose_name='卖家回复')),
                ('seller_reply_time', models.DateTimeField(blank=True, null=True, verbose_name='卖家回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reviews', to='orders.order', verbose_name='订单')),
                ('reviewed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='被评价者')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价者')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehicles.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '评价',
                'verbose_name_plural': '评价',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vehicles.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorites',
            },
        ),
        migrations.AddIndex(
            model_name='carbrand',
            index=models.Index(fields=['name'], name='car_brands_name_4047b4_idx'),
        ),
        migrations.AddIndex(
            model_name='carbrand',
            index=models.Index(fields=['is_active'], name='car_brands_is_acti_fb6983_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclephoto',
            index=models.Index(fields=['vehicle', 'is_main'], name='vehicle_pho_vehicle_15d74b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'status'], name='vehicles_brand_i_28705c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['seller', 'status'], name='vehicles_seller__1fb74e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', '-created_at'], name='vehicles_status_4cdff1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-view_count'], name='vehicles_view_co_0f1446_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_user', '-created_at'], name='reviews_reviewe_44748e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['vehicle', '-rating'], name='reviews_vehicle_28e495_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='favorites_user_id_f73cef_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['vehicle'], name='favorites_vehicle_fea2d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'vehicle')},
        ),
    ]
