# Generated by Django 4.2 on 2025-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='买家电话'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='配送地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='期望送达时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='车辆颜色'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_model_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='车辆款型'),
        ),
    ]
